name: open-machine-learning-jupyter-book
channels:
  - conda-forge
dependencies:
  - python=3.9
  - nbmake
  - pip
  - pip:
    - sphinx==4.5.0
    - pytest==7.2.0
    - pandas==1.5.2
    - numpy==1.24.1
    - matplotlib==3.6.2
    - pywaffle==1.1.0
    - scikit-learn==1.2.0
    - scipy==1.10.0
    - seaborn==0.12.2
    - tensorflow==2.11.0
    - jupyter-book==0.13.1
    - notebook==6.5.2
    - jupyter_contrib_nbextensions==0.7.0
    - sphinxcontrib-mermaid==0.7.1
    - sphinxcontrib-wavedrom==3.0.4
    - sphinxcontrib-plantuml==0.24.1
    - sphinxcontrib-tikz==0.4.16
    - sphinxcontrib-blockdiag==3.0.0
    - sphinxcontrib-drawio==0.0.16
    - git+https://github.com/bonartm/sphinxcontrib-quizdown.git
    - jupyterlite-core==0.1.0b19
    - jupyterlite-pyodide-kernel==0.0.5
    - jupyterlab~=3.5.1
    - jupyterlite-xeus-sqlite==0.2.1
    - jupyterlite-p5-kernel==0.1.0
    - jupyterlite-xeus-lua==0.3.1
    
